accounts/urls.py
from django.conf.urls import url

from .views import RegisterView, IndexView, UpdateUserView, UpdatePasswordView


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^registro/$', RegisterView.as_view(), name='register'),
    url(r'^alterar-dados/$', UpdateUserView.as_view(), name='update_user'),
    url(r'^alterar-senha/$', UpdatePasswordView.as_view(), name='update_password'),
]

catalog/urls.py
from django.conf.urls import url

from .views import ProductListView, CategoryListView, product

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='product_list'),
    url(r'^(?P<slug>[\w_-]+)/$', CategoryListView.as_view(), name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', product, name='product'),
]

checkout/urls.py
from django.conf.urls import url
from .views import CreateCartItemView, CartItemView


urlpatterns = [
    url(r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', CreateCartItemView.as_view(), name='create-cartitem'),
    url(r'^carrinho/$', CartItemView.as_view(), name='cart_item')
]

core/urls.py
from django.conf.urls import url, include

from .views import IndexView, contact

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    # url(r'^registro/$', RegisterView.as_view(), name='registro'),
    url(r'contact/$', contact, name='contact'),
    url(r'catalogo/', include('catalog.urls', namespace='catalog')),
]

market/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^compras/', include('checkout.urls', namespace='checkout')),
    url(r'^entrar/$', login, name='login'),
    url(r'^sair/$', logout, {'next_page': 'index'}, name='logout'),

]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())

    # def __init__(self, *args, **kwargs):
    #     super(ContactForm, self).__init__(*args, **kwargs)
    #     self.fields['name'].widget.attrs['class'] = 'form-control'
    #     self.fields['email'].widget.attrs['class'] = 'form-control'
    #     self.fields['message'].widget.attrs['class'] = 'form-control'

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse_lazy

from .forms import ContactForm

User = get_user_model()

class IndexView(TemplateView):
    template_name = 'index.html'

#
# def index(request):
#     return render(request, 'index.html')


def contact(request):
    form = ContactForm()
    context = {
        'form': form
    }
    return render(request, 'contact.html', context)

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Django E-Commerce{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen"/>
    <link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen"/>
    <link rel="stylesheet" href="{% static 'assets/extra.css' %}" media="screen" />
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a href="{% url 'index' %}" class="navbar-brand">Django E-Commerce</a>
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">Início</a>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}"
                       id="download">Categorias <span class="caret"></span></a>
                    <ul class="dropdown-menu" aria-labelledby="download">
                        {% for category in categories %}
                            <li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li>
                    <a href="{% url 'contact' %}">Contato</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="#">Minha Conta</a></li>
                    <li><a href="{% url 'logout' %}">Sair</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Entrar</a></li>
                    <li><a href="{% url 'accounts:register' %}">Registro</a></li>
                {% endif %}
                <li><a href="{% url 'checkout:cart_item' %}">Carrinho</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="container">
    {% block messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endblock %}
    {% block container %}
    {% endblock %}
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <ul class="list-unstyled">
                    <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
                    <li><a href="">Início</a></li>
                    <li><a href="">Produtos</a></li>
                    <li><a href="">Contato</a></li>
                    <li><a href="">Termos e Privacidade</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

core/templates/contact.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    Contato | {{ super.block }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Fale conosco</h1>
    <form class="form-horizontal">{% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.erros %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.erros %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}     
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

core/templates/index.html
{% extends 'base.html' %}

{% block container %}
    <div class="jumbotron page-header">
        <h1>Django E-Commerce</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua.</p>
        <p><a class="btn btn-primary">Saiba mais</a></p>
    </div>
{% endblock %}

core/templates/pagination.html
<div class="row">
    <div class="col-md-12">
        <nav>
            <ul class="pagination">
                {% for page in paginator.page_range %}
                 <li{% if page_obj.number == page  %} class="active page-item"{% endif %}><a class="page-link" href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
                {% endfor %}
            </ul>
        </nav>
    </div>
</div>

core/templates/product.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}